/*!
 * ga stopwords addon for JavaScript tag cloud builder v0.2
 * http://tagsonflags.com/
 *
 * Copyright 2013.03.01, Oleg Mazko
 * http://www.opensource.org/licenses/bsd-license.html
 */
(function() {
var stopwords = {
"a" : null,
"ach" : null,
"ag" : null,
"agus" : null,
"an" : null,
"aon" : null,
"ar" : null,
"\u00e1r" : null,
"arna" : null,
"as" : null,
"ba" : null,
"beirt" : null,
"b\u00far" : null,
"caoga" : null,
"c\u00e9ad" : null,
"ceathair" : null,
"ceathrar" : null,
"cois" : null,
"comh" : null,
"ct\u00f3" : null,
"cuig" : null,
"c\u00faig" : null,
"c\u00faigear" : null,
"cun" : null,
"d\u00e1" : null,
"daichead" : null,
"dar" : null,
"d\u00e1r" : null,
"de" : null,
"deich" : null,
"deichni\u00far" : null,
"den" : null,
"do" : null,
"d\u00f3" : null,
"don" : null,
"\u00e9" : null,
"\u00e9is" : null,
"faoi" : null,
"faoin" : null,
"faoina" : null,
"faoin\u00e1r" : null,
"fara" : null,
"fiche" : null,
"gach" : null,
"gan" : null,
"go" : null,
"gur" : null,
"haon" : null,
"hocht" : null,
"i" : null,
"\u00ed" : null,
"iad" : null,
"idir" : null,
"in" : null,
"ina" : null,
"in\u00e1r" : null,
"ins" : null,
"is" : null,
"le" : null,
"leis" : null,
"lena" : null,
"len\u00e1r" : null,
"mar" : null,
"m\u00e9" : null,
"mo" : null,
"na" : null,
"n\u00e1" : null,
"nach" : null,
"naoi" : null,
"naon\u00far" : null,
"n\u00ed" : null,
"n\u00edor" : null,
"n\u00f3" : null,
"n\u00f3cha" : null,
"\u00f3" : null,
"och" : null,
"ocht" : null,
"\u00f3n" : null,
"\u00f3na" : null,
"\u00f3n\u00e1r" : null,
"os" : null,
"roimh" : null,
"sa" : null,
"s\u00e9" : null,
"seach" : null,
"seacht" : null,
"seacht\u00f3" : null,
"seasca" : null,
"seisear" : null,
"s\u00ed" : null,
"siad" : null,
"sibh" : null,
"sinn" : null,
"sna" : null,
"tar" : null,
"t\u00ed" : null,
"tr\u00ed" : null,
"tr\u00edna" : null,
"tr\u00edn\u00e1r" : null,
"tr\u00edocha" : null,
"tri\u00far" : null,
"t\u00fa" : null,
"um" : null
};
Taggregator.addStopList('ga', stopwords);
}());
