/*!
 * sv stopwords addon for JavaScript tag cloud builder v0.2
 * http://tagsonflags.com/
 *
 * Copyright 2013.03.01, Oleg Mazko
 * http://www.opensource.org/licenses/bsd-license.html
 */
(function() {
var stopwords = {
"all" : null,
"allt" : null,
"\u00e4n" : null,
"\u00e4r" : null,
"\u00e5t" : null,
"att" : null,
"av" : null,
"blev" : null,
"bli" : null,
"blir" : null,
"blivit" : null,
"d\u00e5" : null,
"d\u00e4r" : null,
"de" : null,
"dem" : null,
"den" : null,
"denn" : null,
"der" : null,
"dess" : null,
"det" : null,
"dett" : null,
"dig" : null,
"din" : null,
"ditt" : null,
"du" : null,
"eft" : null,
"ej" : null,
"ell" : null,
"en" : null,
"er" : null,
"era" : null,
"ert" : null,
"ett" : null,
"f\u00f6r" : null,
"fr\u00e5n" : null,
"ha" : null,
"had" : null,
"han" : null,
"har" : null,
"h\u00e4r" : null,
"henn" : null,
"hon" : null,
"honom" : null,
"hur" : null,
"i" : null,
"ick" : null,
"ing" : null,
"inom" : null,
"int" : null,
"jag" : null,
"ju" : null,
"kan" : null,
"kund" : null,
"man" : null,
"med" : null,
"mellan" : null,
"men" : null,
"mig" : null,
"min" : null,
"mitt" : null,
"mot" : null,
"mycket" : null,
"n\u00e5gon" : null,
"n\u00e5got" : null,
"n\u00e5gr" : null,
"n\u00e4r" : null,
"ni" : null,
"nu" : null,
"och" : null,
"om" : null,
"oss" : null,
"\u00f6ver" : null,
"p\u00e5" : null,
"s\u00e5" : null,
"s\u00e5dan" : null,
"s\u00e5dant" : null,
"samm" : null,
"sedan" : null,
"sig" : null,
"sin" : null,
"sitt" : null,
"sj\u00e4lv" : null,
"skull" : null,
"som" : null,
"till" : null,
"und" : null,
"upp" : null,
"ut" : null,
"utan" : null,
"vad" : null,
"var" : null,
"v\u00e5r" : null,
"varf\u00f6r" : null,
"varit" : null,
"varj" : null,
"vart" : null,
"v\u00e5rt" : null,
"vem" : null,
"vi" : null,
"vid" : null,
"vilk" : null,
"vilket" : null
};
Taggregator.addStopList('sv', stopwords);
}());
